### ISSUE TITLE
Dataset collection template

### ISSUE THREAD

**Issue by siwelisabeth** [gbif/hosted-portals#32] opened 2021-03-01 08:02 UTC
The LivingNorway hosted portal would like to request a template for a dataset collection page. The page can be configured to show a table of selected datasets. The table will be populated via JavaScript by querying GBIF API using a pre-defined filter.

**Comment by MortenHofft** [comment] 2021-03-01 08:48
Hi @siwelisabeth 
I think this can be considered a duplicate of https://github.com/gbif/hosted-portals/issues/19
So I'm closing this issue. If you disagree, then please say so, then I will open this issue again

But in short: yes - we should probably add a more dedicated dataset search than the dataset tab on occurrences (which is a list of the datasets containing occurrences for a given occurrence filter)

**Closed by MortenHofft** 2021-03-01 08:48 UTC
