### ISSUE TITLE
Mobile bug fot total counts transaltions

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#186] opened 2021-09-27 19:45 UTC
The total counts are shown correctly on desktop but the code is shown in mobile devices

**desktop**

<img width="376" alt="Captura de Pantalla 2021-09-27 a la(s) 2 44 46 p  m" src="https://user-images.githubusercontent.com/5700527/134974730-bf1d4323-b412-466c-b9c8-e4af13104048.png">
**mobile**
<img width="372" alt="Captura de Pantalla 2021-09-27 a la(s) 2 45 05 p  m" src="https://user-images.githubusercontent.com/5700527/134974719-f8cadf27-1731-404a-800c-3d45c4bd7ef8.png">

**Comment by MortenHofft** [comment] 2021-09-28 14:38
I'm unable to replicate this.
Could you possibly provide:
* Link to broken page
* Device type and model
* Operating system and version
* Browser and version

Thank you

**Comment by MortenHofft** [comment] 2021-12-06 14:44
Closed as I'm unable to reproduce and need more information to progress

**Closed by MortenHofft** 2021-12-06 14:44 UTC
Labels: Type: Bug, Needs clarification, Section: Data exploration
